
export default {
  NAME: 'Wellington Lima',
  EMAIL: 'agenciasupermix@gmail.com',
  PAGARME_CODE: '',
  API_KEY_TEST: '',
  ENCRYPTION_KEY_LIVE: '',
  ENCRYPTION_KEY_TEST: '',
  CARD_NUMBER: '5565194896463038',
  CARD_HOLDER_NAME: 'Well Lima',
  CARD_EXPIRATION_DATE: '1120',
  CARD_CVV: '761',
  RECIPIENT_ID1: '',
  RECIPIENT_ID2: '',
  ADDRESS_COUNTRY: 'BR',
  ADDRESS_STATE: 'RJ',
  ADDRESS_CITY: 'RIO DE JANEIRO',
  ADDRESS_NEIGHBORHOOD: 'MADUREIRA',
  ADDRESS_STREET: 'RUA CONSELHEIRO GALVÃO',
  ADDRESS_STREET_NUMBER: '100',
  ADDRESS_ZIPCODE: '21360000'
}
