
export default {
  NAME: 'Well Lima',
  PAGARME_CODE: '',
  API_KEY_TEST: '',
  ENCRYPTION_KEY_LIVE: '',
  ENCRYPTION_KEY_TEST: '',
  CARD_NUMBER: '5565194896463038',
  CARD_HOLDER_NAME: 'Well Lima',
  CARD_EXPIRATION_DATE: '1120',
  CARD_CVV: '761'
}
	